global:
        #smtp_smarthost: "localhost:25"
        #smtp_from: "alertmanager@example.org"
        slack_api_url: https://hooks.slack.com/services/TSQRKEHD2/B015VJWT468/pnc4zEcsPevwpay3d9U

        #templates:
        #- "alerts-template.tmpl"

route:
  group_by: ["alertname"]

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: team

  routes:
    - match_re:
        service: ^(kubernetes|k8s)$
      receiver: infrastructure

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "cluster", "service"]

receivers:
  - name: "infrastructure"
    email_configs:
      - to: "oncall-critical@example.com"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "high"
    target_match:
      severity: "warning"
    equal: ["alertname", "cluster", "service"]

receivers:
  - name: "infrastructure"
    email_configs:
      - to: "oncall-high@example.com"
        send_resolved: true

