global:
        #smtp_smarthost: "localhost:25"
        #smtp_from: "alertmanager@example.org"
        slack_api_url: https://hooks.slack.com/services/TSQRKEHD2/B015VJWT468/pnc4zEcsPevwpay3d9U

        #templates:
        #- "alerts-template.tmpl"

route:
  group_by: ["alertname"]

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: critical
  routes:
  - match:
     severity: high
     service: ^(kubernetes|k8s)$
     receiver: high
  - match:
     security: true
    receiver: critical

inhibit_rules:
  - source_match:
      severity: critical, high
    target_match:
      severity: "warning"
    equal: ["alertname", "cluster", "service"]

receivers:
  - name: "critical"
    email_configs:
      - to: "oncall-critical@example.com"
        send_resolved: true
  - name: "high"
    email_configs:
      - to: "oncall-high@example.com"
        send_resolved: true
