version: "3.1"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/conf/prometheus/
    command:
      - "--config.file=/conf/prometheus/config.yaml"
    links:
      - alertmanager:alertmanager
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/conf/alertmanager/
    command:
      - "--config.file=/conf/alertmanager/config.yaml"
    restart: always
