{
 "title": "Prometheus Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Deployment_var",
    "label": "Deployments Disponibles",
    "query": "label_values(kube_deployment_created,deployment)"
   },
   {
    "name": "pods_deployment_var",
    "label": "Pods",
    "query": "label_values(kube_pod_container_info{container=~\"$Deployment_var\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "RESTART FROM \"$Deployment_var\"",
   "type": "singlestat",
   "description": "SUMA DE REINICIOS TOTALES DE LOS PODS DEL DEPLOYMENT SELECCIONADO",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"$Deployment_var\"})"
    }
   ]
  },
  {
   "title": "NUMBER POD RESTARTS FROM \"$Deployment_var\"",
   "type": "bargauge",
   "description": "Obtenemos número de reinicios de cada pod",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "repeat": "Deployment_var",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$pods_deployment_var\",container=~\"$Deployment_var\"}",
     "legendFormat": "$pods_deployment_var"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "repeat": "pods_deployment_var",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "MEMORY USE  FROM \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Sumo de uso de memoria de los pods seleccionados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "CPU USE DEPLOYMENT \"$Deployment_var\" / \"$pods_deployment_var\"",
   "type": "graph",
   "description": "Nos muestra el uso de cpu de los deployments",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 112 },
   "repeat": "Deployment_var",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_system_seconds_total{container_label_io_kubernetes_pod_name=~\"$pods_deployment_var\",container_label_io_kubernetes_container_name=\"$Deployment_var\"})",
     "legendFormat": "TOTAL CPU DEPLOYMENT"
    }
   ]
  }
 ]
}