groups:
  - name: api
    rules:
      - alert: APIHighRequestLatency
        expr: api_http_request_latencies_second > 1
        for: 10m
        labels:
          severity: high
          team: web
        annotations:
          summary: "High request latency on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a request latency above 1s (current value: {{ $value }}s)"

  - name: kubernetes
    rules:
      - alert: k8s_pods_pending
        expr: kube_pod_status_phase{phase="Pending"} == 1
        for: 2m
        labels:
          team: "infrastructure"
        annotations:
          summary: "Pods are in pending state"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in pending state for more than 2 minutes."
      - alert: k8s_pods_failed
        expr: kube_pod_status_phase{phase="Failed"} == 1
        for: 10m
        labels:
          team: "infrastructure"
        annotations:
          summary: "Pods are in failed state"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in failed state for more than 2 minutes."

  - name: nodes
    rules:
      # The count of CPUs per node.
      - record: instance:node_cpus:count
        expr: count(node_cpu_seconds_total{mode="idle"}) without (cpu,mode)

      # CPU in use by CPU.
      - record: instance_cpu:node_cpu_seconds_not_idle:rate5m
        expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) without (mode)

      # CPU in use by mode.
      - record: instance_mode:node_cpu_seconds:rate5m
        expr: sum(rate(node_cpu_seconds_total[5m])) without (cpu)

      # CPU in use ratio.
      - record: instance:node_cpu_utilization:ratio
        expr: sum(instance_mode:node_cpu_seconds:rate5m{mode!="idle"}) without (mode) / instance:node_cpus:count
